### PR TITLE
current wind and upgrade to charJS

### PR DESCRIPTION
**Pull request by liorz901**
- added panel for current wind
- updated the version of chart JS to the latest. This will enable us many more features for the graph.
- minor css changes

### CODE REVIEW

**Comment by liorz901** [comment]
oh oh it looks like I need to resolve some conflicts before I can merge this one . I will continue tomorrow

**Comment by liorz901** [comment]
Screenshot 2024-04-16 at 9 26 34 AM
@pdxalz  I fixed the issue, please review and merge

**Comment by pdxalz** [comment]
Your changes are live now. I’m Still having the left justified text issue
though.

**Comment by liorz901** [comment]
on which phone or browser ?

Thanks for merging . I am stocked about the next branch ....

**Comment by pdxalz** [comment]
It happens on desktop chrome, and firefox and chrome on the iphone, for
both the real server and also my home server.

Alan

**Comment by liorz901** [comment]
I see it on the server code on chrome but it is working fine locally on
Chrome , weird
I will fix it
Lior

**Comment by liorz901** [comment]
btw when you upload to the server do you upload all the files including the
CSS file.
I see style css is not loading on the server , maybe a path issue

**Comment by liorz901** [comment]
I create PR #3
lets see if this is fixes it for the server side (and your local)

**Pull request merged**
